### PR TITLE
Update Generation Script and add new Emoticons

### PR DESCRIPTION
**Pull request by watbe**
Hi @bontscho, thanks for your work on this repository! I noticed it was no longer up-to-date so I looked into it.

The changes in this PR includes the new emoticons and also updates the script to support new types of emoticons - team emoticons. However, this PR also makes it more difficult to update the emoticons without external dependencies. Read on.

You might have noticed that new emoticons are no longer available in the `dotabuff/d2vpkr` dependency - that is because Valve is only updating assets in panorama now. Dotabuff uses a **private** repository for these assets. This repository is not available for general public use because we are concerned about copyright issues.

The script will no longer run if you don't have a local folder of the emoticons - you will have to obtain the source files for the emoticons yourself (i.e, extract the VPKs yourself). Also, the naming of the files in `dotabuff/panorama` is different - we append the original asset extension so it results in files named like `slug_png.png`.

Alternatively, I can create a new PR with just the emoticon updates and no changes to the generation script - but this means that people won't be able to reproduce builds (including the pro team stuff).

### CODE REVIEW

**Comment by watbe** [comment]
This will probably need some documentation in the README.md if you agree to use the updated generation script. Namely that you need to have the emoticon sources in a local folder and point use an environment variable to point to it.

**Comment by bontscho** [comment]
thanks for your work, this looks good :) if you want you can update the README aswell with this PR and i'll wave it right through, since i am currently not maintaining this project

**Comment by watbe** [comment]
Updated the readme, thanks for the review!

**Comment by bontscho** [comment]
cheers mate 🍺

**Pull request merged**
