### PR TITLE
TI5 Charms

### PR DESCRIPTION
**Pull request by d-chen**
I was wondering why the script was exploding on my PC. Turns out it doesn't like Windows line endings. :)

### CODE REVIEW

**Comment by bontscho** [comment]
thanks for the PR :beer: , can you specify what caused the explosion so i can fix it maybe?

**Comment by bontscho** [comment]
facepalm, i shouldnt look at PRs before i had my cofffee :disappointed:

**Comment by d-chen** [comment]
I originally extracted emoticons.txt on a Windows device. Re-saved it with Linux line enders and the script ran fine afterwards. My command line doesn't seem to be giving me the full error message without cropping part of it off.

```
E:\Git\dota2-chat-emoticons>ruby generate.rb
C:/Ruby21/lib/ruby/gems/2.1.0/gems/vdf4r-0.1.2/lib/vdf4r/parser.rb:43:in `block in parse': ungrammatical content at line 1: 'ÿ_" e m o t i c o n s "
'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/vdf4r-0.1.2/lib/vdf4r/parser.rb:
39:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/vdf4r-0.1.2/lib/vdf4r/parser.rb:
39:in `each_with_index'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/vdf4r-0.1.2/lib/vdf4r/parser.rb:
39:in `parse'
        from generate.rb:8:in `block in <main>'
        from generate.rb:6:in `open'
        from generate.rb:6:in `<main>'
```

**Comment by bontscho** [comment]
thanks for the details. @manveru already made this obsolete by using the online json version from d2vpk https://github.com/bontscho/dota2-chat-emoticons/pull/7 :smile:

**Pull request merged**
